# Generated by Django 6.0.2 on 2026-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombo', models.IntegerField(max_length=6, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('id_remoto', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
