# Generated by Django 6.0.2 on 2026-03-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_tombo'),
        ('tecnico', '0003_alter_tecnico_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField()),
                ('solucao', models.TextField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('data', models.DateField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnico.tecnico')),
            ],
        ),
    ]
