# Generated by Django 6.0.2 on 2026-03-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='observacao',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
