# Generated by Django 6.0.2 on 2026-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='matricula',
            field=models.CharField(default=2020, max_length=13),
            preserve_default=False,
        ),
    ]
