# Generated by Django 6.0.2 on 2026-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_tecnico_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='matricula',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
